# Generated by Django 5.2.5 on 2025-08-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation_en', models.TextField()),
                ('explanation_fa', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('media_type', models.CharField(max_length=20)),
            ],
        ),
    ]
