# Generated by Django 5.2.5 on 2025-09-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation_en', models.TextField()),
                ('explanation_fa', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('media_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeoWs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasa_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=264)),
                ('EsDiameter', models.CharField(max_length=10)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('miss_distance', models.CharField(max_length=20)),
                ('nearest_approach', models.CharField(max_length=20)),
                ('relative_speed', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
