# Generated by Django 5.2.5 on 2025-09-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neows',
            name='nasa_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
