# Generated by Django 5.2.5 on 2025-09-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeoWs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('EsDiameter', models.CharField(max_length=10)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('miss_distance', models.CharField(max_length=20)),
                ('nearest_approach', models.CharField(max_length=20)),
                ('relative_speed', models.CharField(max_length=20)),
            ],
        ),
    ]
