# Generated by Django 5.2.5 on 2025-09-05 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_neows'),
    ]

    operations = [
        migrations.AddField(
            model_name='neows',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
