# Generated by Django 5.2.5 on 2025-09-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_alter_neows_nasa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neows',
            name='date',
            field=models.DateField(),
        ),
    ]
