# Generated by Django 5.2.5 on 2025-09-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_alter_neows_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neows',
            name='EsDiameter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='neows',
            name='miss_distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='neows',
            name='nearest_approach',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='neows',
            name='relative_speed',
            field=models.FloatField(),
        ),
    ]
