# Generated by Django 5.2.5 on 2025-09-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_neows_esdiameter_alter_neows_miss_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neows',
            name='nearest_approach',
            field=models.CharField(max_length=50),
        ),
    ]
