# Generated by Django 5.2.5 on 2025-09-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_alter_neows_nearest_approach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('Position', models.CharField(max_length=264)),
                ('description', models.TextField()),
                ('github', models.CharField(max_length=400)),
                ('instagram', models.CharField(max_length=400)),
                ('telegram', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
