# Generated by Django 5.2.5 on 2025-09-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='profile',
            field=models.ImageField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
    ]
